#!/usr/bin/env python3
"""Replace only bounded mosquito fragments in the canonical manuscript."""

from __future__ import annotations

import argparse
import json
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
MANUSCRIPT = ROOT / "paper" / "manuscript"
VARIANTS = ROOT / "paper" / "anopheles_variants"
def replace_slot(text: str, slot: str, replacement: str) -> str:
    begin = f"% ANOPHELES_SLOT_BEGIN {slot}\n"
    end = f"\n% ANOPHELES_SLOT_END {slot}"
    left = text.index(begin) + len(begin)
    right = text.index(end, left)
    return text[:left] + replacement.rstrip() + text[right:]


def clear_variant_owned_overlays() -> None:
    """Remove only paths declared by the Phase 2 overlay."""
    owned: set[Path] = set()
    overlay_root = VARIANTS / "phase2" / "manuscript"
    for directory in ("generated", "figures", "tables"):
        source_dir = overlay_root / directory
        if not source_dir.is_dir():
            continue
        for source in source_dir.rglob("*"):
            if source.is_file():
                owned.add(source.relative_to(overlay_root))
    for relative in sorted(owned):
        target = MANUSCRIPT / relative
        if target.is_file():
            target.unlink()


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("variant", choices=("phase2",))
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    root = VARIANTS / "phase2"
    config = json.loads((root / "config.json").read_text())
    if config["status"] != "complete" or not config["submission_eligible"]:
        raise SystemExit("Phase 2 has not passed its submission gate")
    fragment_root = root / "fragments"
    fragments = sorted(fragment_root.glob("*.tex"))
    if not fragments:
        raise SystemExit(f"no fragments found in {fragment_root}")
    grouped: dict[str, list[Path]] = {"main": [], "si": []}
    for fragment in fragments:
        document, _slot = fragment.stem.split("_", 1)
        grouped[document].append(fragment)
    for document, paths in grouped.items():
        target = MANUSCRIPT / f"{document}.tex"
        text = target.read_text()
        for fragment in paths:
            slot = fragment.stem[len(document) + 1:]
            text = replace_slot(text, slot, fragment.read_text())
        if not args.check:
            target.write_text(text)
    overlay_root = root / "manuscript"
    if not args.check and overlay_root.is_dir():
        clear_variant_owned_overlays()
        for directory in ("generated", "figures", "tables"):
            source_dir = overlay_root / directory
            if not source_dir.is_dir():
                continue
            for source in source_dir.rglob("*"):
                if source.is_file():
                    destination = MANUSCRIPT / source.relative_to(overlay_root)
                    destination.parent.mkdir(parents=True, exist_ok=True)
                    shutil.copy2(source, destination)
    if not args.check:
        (MANUSCRIPT / "anopheles_variant.tex").write_text(
            f"% Generated by switch_variant.py\n\\def\\AnophelesVariant{{{args.variant}}}\n"
        )
    print(f"Anopheles variant {'checked' if args.check else 'activated'}: {args.variant}")


if __name__ == "__main__":
    main()
